#Nerys Jimenez Pichardo
#Makefile
#CSC 381, The College of Saint Rose

queue_test: queue.c queue.h queue_test.c
	gcc -g -Wall -o queue_test queue.c queue.h queue_test.c

clean::
	/bin/rm -f queue_test